### ISSUE TITLE
Change folder permission

### ISSUE THREAD

**Issue by brenoos** [weibeld/heroku-buildpack-run#5]
Hello.
I installed this buildpack and test the hello world (worked").
Put i need to execute chmod 777 -R Storage, to change my folder permisson.
the script executed successful, but after deployed, when I execute: heroku run "ls -la" to see the permissions, the permissions aren't set.

Can you help me?

**Comment by weibeld** [comment]
Hi, yes, the permissions will not be set, because the build is performed in a separate sandboxed *build container*, and changes you make to the environment of this build container (e.g. environment variables and file permissions) are not propagated to the production containers (dynos), only the raw files of your application are copied to the production dynos.

The solution to your problem is to use a `.profile` file: create the file `.profile` in the root directory of your app and put the command `chmod -R 777 Storage` in it. This file will be sourced at the startup of each *production dyno*, and your permissions will be set at production time. This is described [here](https://devcenter.heroku.com/articles/dynos#the-profile-file).

**Comment by brenoos** [comment]
Thanks for the help man =)

**Comment by weibeld** [comment]
Good to know that it worked for you 👍

**Comment by wanghaisheng** [comment]
@weibeld  sir  a little help 
i got procfile like 
```
web: chmod 777 docker_build.sh && ./docker_build.sh && python main.py --port=$PORT
```

after deploy  run  ls -al  it still rwx 

-rwx------ 1 u59997 dyno 12605504 Apr 13 21:11 ./ksubdomain

when build it is 
-rwxrwxrwx 1 root root 12605504 Apr  7 09:56 ./ksubdomain
