### ISSUE TITLE
BUILDPACK_RUN Custom Script Name with Parameters

### ISSUE THREAD

**Issue by danieltjewett** [weibeld/heroku-buildpack-run#6]
Is there a way to do something like this:

```
BUILDPACK_RUN="myfile.sh parameter:myfile.sh anotherparameter"
```

**Comment by weibeld** [comment]
Good idea. It's possible now, see [README](https://github.com/weibeld/heroku-buildpack-run#usage-with-arguments).

Also, a little change is that the scripts are now executed by a sub-shell (with `bash script.sh`), rather than sourced in the current shell. But this shouldn't make a difference for most use cases.

Let me know if it works correctly.

**Comment by danieltjewett** [comment]
@weibeld very nice!  Works great!
