### ISSUE TITLE
Buildpack failing during Heroku build

### ISSUE THREAD

**Issue by andreipetre** [weibeld/heroku-buildpack-run#9]
The buildpack has stopped working (on Heroku) today, with the following error:

```
Running: ./buildpack-run.sh
/app/tmp/buildpacks/d4963cfdc610c1afed0921a93443e079284fcd2706707c8a33c3d1220c492dbfcb751a745f252dfc67a3828cf1f3cdd01d6bf5d0fc25fa0b511b62c391305643/bin/compile: line 61: ./buildpack-run.sh: Permission denied
-----> Aborting build because './buildpack-run.sh' exited with a non-zero code (126)
```

I'm using `buildpack-run.sh` to run custom commands. I've made several deploys to Heroku yesterday which all worked fine. I've not made any changes to `buildpack-run.sh` which makes me think that something in the commits on 9 Oct is responsible. The error message would indicate it's on [line 61](https://github.com/weibeld/heroku-buildpack-run/blob/master/bin/compile#L61).

To illustrate the problem, even a `buildpack-run.sh` file with

```shell
#!/bin/sh

echo "-----> Run custom steps"
```

fails to build on Heroku (with the same error message).

**Comment by whenchyiv** [comment]
Seeing this as well.

EDIT: Seems to be an issue with the new release - reverting to the old release works fine.

**Comment by andreipetre** [comment]
Solution for now is to specify a previous commit for the buildpack

```
https://github.com/weibeld/heroku-buildpack-run.git#ee9f6c3b5a22d3e95764e4605ebce6895cf11073
```

This works for me and is [recommended by Heroku](https://devcenter.heroku.com/articles/buildpacks#using-a-third-party-buildpack) as good practice.

**Comment by Macleykun** [comment]
Same issue aswell, thx for the temporary fix above!

**Comment by Macleykun** [comment]
https://github.com/weibeld/heroku-buildpack-run/commit/e093a0819beac2b2202fbfc7c6f60908141629fd
I believe this is the commit in question that is causing this, normally bash <script> works.
./<script> always results in a permission error.
bash ./<script> normally works.

Commented if the above could be chosen instead.

**Comment by weibeld** [comment]
The latest change requires shell scripts to be executable. This means:

1. Must include a shebang line (`#!/bin/bash` or similar)
2. Must have the executable bit set (`chmod +x buildpack-run.sh`)

This is because the specified commands in `BUILDPACK_RUN` (by default `./buildpack-run.sh`) are now executed rather than sourced by Bash. See [README](https://github.com/weibeld/heroku-buildpack-run#configure).

**EDIT:** better error output is now available in the latest version (indicating if a local file doesn't have the executable bit set).

**Comment by andreipetre** [comment]
Thanks @weibeld. Can confirm your suggestions work.
